AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LocalStack SAM Application with Python Lambda Functions

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 256
    Environment:
      Variables:
        ENVIRONMENT: local

Resources:
  CustomUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: custom-utils-layer
      Description: Shared utilities layer with response formatting and greeting functions
      ContentUri: layers/custom_utils/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-world-function
      CodeUri: src/handlers/hello_world/
      Handler: app.lambda_handler
      Description: Simple Lambda function demonstrating Lambda Layer integration
      Layers:
        - !Ref CustomUtilsLayer
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
